astro/urls.py
from django.contrib import admin

from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetView

from django.urls import path, include

from astro.views import errors
from astro.views import contact
from astro.views import index

from astro.views.webservices import geonames
from astro.views.registration import authentication

handler404 = errors.page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('authentication/', authentication, name='authentication'),
    path('password_reset', PasswordResetView.as_view(), name='password_reset'),
    path('', index.default_view, name='index'),
    path('contact/', contact.default_view, name='contact'),
    path('geo/service/', geonames.default_view, name='geoname'),
    path('theme/', include('theme.urls')),
    path('aspects/', include('aspects.urls')),
]

# bokeh_base_path = settings.BOKEH_BASE_PATH
#
# bokeh_apps = [
#     document("aspects/activation", views.activation_view),
# ]
#
#
# urlpatterns += static_extensions()
# urlpatterns += staticfiles_urlpatterns()

theme/urls.py
from django.urls import path

from theme.views.celebrities import themes as celebrities_themes
from theme.views.celebrities import transits as celebrities_transits
from .views import themes
from .views.reports import generate_pdf

app_name = 'theme'


urlpatterns = [

    path('', celebrities_themes.celebrities, name='celebrities'),

    path('<int:pk>/', celebrities_themes.DetailCelebrity.as_view(), name='theme'),

    path('new/', themes.new, name='new'),
    path('save/', themes.save, name='save'),
    # path('transit/', celebrities.DetailCelebrity.as_view(), name='transit'),
    path('<int:theme_id>/report/', generate_pdf, name='generate_pdf'),

    path('transit/', celebrities_transits.celebrities, name='transit_celebrities'),
    path(
        'transit/<int:pk>/',
        celebrities_transits.Detail.as_view(),
        name='transit',
    ),
    path(
        'transit/',
        celebrities_transits.Detail.as_view(),
        name='celebrity_transit',
    ),
]

astro/db/connection/cursor/models.py
# -*- coding: utf-8 -*-
##################################
#  @program        synda
#  @description    climate models data transfer program
#  @copyright      Copyright "(c)2009 Centre National de la Recherche Scientifique CNRS.
#                             All Rights Reserved"
#  @license        CeCILL (https://raw.githubusercontent.com/Prodiguer/synda/master/sdt/doc/LICENSE)
##################################
import sqlite3
import itertools

from synda.source.db.connection.models import Connection
from synda.source.db.connection.exceptions import DataIntegrityError, DataUnexpectedError
from synda.source.db.connection.cursor.exceptions import CursorNotAvailable


class Cursor(Connection):

    def __init__(self, full_filename=""):
        super(Cursor, self).__init__(full_filename=full_filename)
        self.db_cursor = None
        self.set_db_cursor()

    def set_db_cursor(self):
        if self.get_database_connection():
            try:
                self.db_cursor = self.get_database_connection().cursor()
            except Exception as error:
                raise CursorNotAvailable(
                    "sqlite",
                    error.__str__(),
                )

    def get_db_cursor(self):
        return self.db_cursor

    def execute(self, sql):
        try:
            self.db_cursor.execute(sql)
        except sqlite3.IntegrityError as error:
            self.close()
            raise DataIntegrityError(
                error.__str__(),
            )
        except Exception as error:
            self.close()
            raise DataUnexpectedError(
                error.__str__(),
            )

        return self.db_cursor

    def close(self):
        self.db_cursor.close()
        super(Cursor, self).close()

    def get_data(self):
        desc = self.db_cursor.description
        column_names = [col[0] for col in desc]
        return [
            dict(itertools.izip_longest(column_names, row)) for row in self.db_cursor.fetchall()
        ]


if __name__ == '__main__':

    cursor = Cursor()
    sql_request = "select version from version"
    cursor.execute(sql_request)
    data = cursor.get_data()
    cursor.close()
    pass

astro/db/connection/models.py
# -*- coding: utf-8 -*-
##################################
#  @program        synda
#  @description    climate models data transfer program
#  @copyright      Copyright "(c)2009 Centre National de la Recherche Scientifique CNRS.
#                             All Rights Reserved"
#  @license        CeCILL (https://raw.githubusercontent.com/Prodiguer/synda/master/sdt/doc/LICENSE)
##################################
from sqlalchemy import create_engine, text
from astro.db.config import Config


class Connection(object):

    def __init__(self, timeout=20):

        # init

        self.engine = ""
        self.timeout = 0
        self.db_connection = None
        self.config = Config(init=False)

        # settings

        self.set_engine()
        self.timeout = timeout
        # self.connect()

    def set_engine(self):
        self.config = Config()
        conf = self.config.get()
        self.engine = create_engine(
            'mysql+mysqlconnector://{}:{}@{}:{}/{}'.format(
                conf["user"],
                conf["password"],
                conf["host"],
                conf["port"],
                conf["dbname"],
            ),
            echo=True,
            pool_pre_ping=True,
        )

    def close(self):
        self.db_connection.close()
        self.db_connection = None

    def get_database_connection(self):
        return self.db_connection

    def set_db_connection(self, db_connection):
        self.db_connection = db_connection

    def connect(self):

        try:
            self.db_connection = sqlite3.connect(self.full_filename, self.timeout)
            # this is for "by name" colums indexing
            self.db_connection.row_factory = sqlite3.Row

        except (Exception, sqlite3.DatabaseError) as error:
            raise DatabaseNotFound(
                error.__str__(),
            )

    def is_valid(self):
        return isinstance(self.db_connection, sqlite3.Connection)

    def commit(self):
        self.db_connection.commit()

    def execute(self, sql_requests):

        if isinstance(sql_requests, str):
            sql_requests = [sql_requests]
        try:
            with self.db_connection:
                for sql_request in sql_requests:
                    self.db_connection.execute(sql_request)
        except sqlite3.IntegrityError as error:
            self.close()
            raise DataIntegrityError(
                error.__str__(),
            )
        except Exception as error:
            self.close()
            raise DataUnexpectedError(
                error.__str__(),
            )


if __name__ == '__main__':

    _conn = Connection()
    with _conn.engine.connect() as conn:
        print(conn.scalar(text("select 'hi'")))
    conn.close()
    pass

astro/db/models.py
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String, DateTime, Boolean
from sqlalchemy.orm import (
    scoped_session, sessionmaker,
)

from pyramid.threadlocal import get_current_registry

from astro.db.conf import get_engine
from astro.db.conf import get_settings

import uuid

DBSession = scoped_session(sessionmaker())
Base = declarative_base()


def create_db(settings):

    db_session = create_db_session(settings)

    engine = get_engine(settings)
    Base.metadata.bind = engine

    # Fixme, find something more elegant
    try:
        db_session.query(User).all()

    except Exception:
        print("Creating database")
        Base.metadata.create_all(engine)

    finally:
        return engine


def create_db_session(settings=None):

    if settings is None:
        settings = get_settings()

    engine = get_engine(settings)

    session = scoped_session(sessionmaker())

    session.configure(bind=engine)
    Base.metadata.bind = engine

    return session


def _create_token():
    return uuid.uuid4().__str__()  # binascii.b2a_hex(os.urandom(20))


def get_pyramid_settings():

    settings = get_current_registry().settings
    return settings  # db_url


def get_db_users(session):

    q = session.query(User)
    if q.count() == 0:
        users = None
    else:
        users = q.all()
    return users


def get_db_user(session, allowed_domain):

    q = session.query(User).filter(User.allowed_domain == allowed_domain)
    if q.count() == 0:
        success = False
        user = None
    else:
        user = q.one()
        success = True

    return success, user


def get_db_user_token(session, allowed_domain):

    q = session.query(User).filter(User.allowed_domain == allowed_domain)
    if q.count() == 0:
        token = None
    else:
        token = q.one().htoken
    return token


def delete_db_user(session, allowed_domain):

    success, user = get_db_user(session, allowed_domain)
    if success:
        session.delete(user)
    return success


def create_db_user(session, username, allowed_domain, allow_sub_domains=False):

    is_found, user = get_db_user(session, allowed_domain)

    if is_found:
        creation = False
    else:
        new_user = User(username, allowed_domain, allow_sub_domains)
        session.add(new_user)
        creation, user = get_db_user(session, allowed_domain)

    return creation, user


def create(model, **kwargs):
    try:
        instance = model(**kwargs)
        DBSession.add(instance)
        DBSession.commit()
    except:
        DBSession.rollback()
        raise
    return instance


def delete(instance):

    DBSession.delete(instance)
    DBSession.commit()


class User(Base):
    __tablename__ = 'users'
    htoken = Column(String, primary_key=True)
    name = Column(String)
    creation_date = Column(DateTime)
    expires = Column(DateTime)
    allowed_domain = Column(String)
    allow_sub_domains = Column(Boolean)

    def __init__(self, name, allowed_domain, allow_sub_domains):
        self.htoken = _create_token()
        self.name = name
        self.allowed_domain = allowed_domain
        self.allow_sub_domains = allow_sub_domains

astro/legend/zodiac/astrological/models.py
# coding=utf-8
"""
Created on 2020, December 19th
@author: orion
"""
from transcend.processes import merge
from transcend.views.charts.graphics.models import Model as GraphicsModel
from transcend.views.charts.theme.models import Model as BaseModel
from astro.legend.zodiac.astrological.constants import COLORS
from astro.legend.zodiac.astrological.constants import BACKGROUND_COLORS


class Model(BaseModel, GraphicsModel):

    def __init__(self, chart, dimensions=None):
        BaseModel.__init__(self, chart)
        GraphicsModel.__init__(self, dimensions=dimensions)

        self.init()

    def init(self):
        self.load_chart()

    def load_chart(self):

        chart = self.get_container()
        chart_name = chart.get_name()

        content = chart.get_content()

        structure = dict(
            colors=dict(
                zodiac=COLORS,
                background=BACKGROUND_COLORS,
            ),
            opacity=1.0,
            visible=True,
            name=chart_name,
            shape=dict(
                visible=True,
                name=chart_name,
                opacity=0.75,
                layer="below",
                line=dict(
                    color='#ddd',
                    width=1,
                ),
            ),
            image=dict(
                x=-0.0125,
                sizex=0.035,
                sizey=0.035,
                xanchor="center",
                yanchor="middle",
                opacity=1.0,
                layer="above",
            ),
        )

        merge(
            structure,
            content,
        )

    def get_data(self):
        return self.get_container()

astro/legend/zodiac/astronomical/models.py
# coding=utf-8
"""
Created on 2020, December 19th
@author: orion
"""
from transcend.processes import merge
from transcend.views.charts.graphics.models import Model as GraphicsModel
from transcend.views.charts.theme.models import Model as BaseModel
from astro.legend.zodiac.astronomical.constants import COLORS


class Model(BaseModel, GraphicsModel):

    def __init__(self, chart, dimensions=None):
        BaseModel.__init__(self, chart)
        GraphicsModel.__init__(self, dimensions=dimensions)

        self.init()

    def init(self):
        self.load_chart()

    def load_chart(self):

        chart = self.get_container()
        chart_name = chart.get_name()

        content = chart.get_content()

        structure = dict(
            colors=COLORS,
            opacity=0.25,
            visible=True,
            name=chart_name,
            shape=dict(
                visible=True,
                name=chart_name,
                opacity=0.75,
                layer="below",
                line=dict(
                    color='#ddd',
                    width=1,
                ),
            ),
            marker=dict(
                name="zodiac names",
                opacity=1.0,
                visible=True,
                color="#000",
            ),
        )

        merge(
            structure,
            content,
        )

    def get_data(self):
        return self.get_container()

astro/legend/zodiac/models.py
# coding=utf-8
"""
Created on 2020, April 27th
@author: orion
"""
from transcend.processes import merge
from transcend.views.charts.graphics.models import Model as GraphicsModel
from transcend.views.charts.theme.models import Model as BaseModel
from transcend.views.charts.theme.zodiac.constants import COLORS


class Model(BaseModel, GraphicsModel):

    def __init__(self, chart, dimensions=None):
        BaseModel.__init__(self, chart)
        GraphicsModel.__init__(self, dimensions=dimensions)

        self.init()

    def init(self):
        self.load_chart()

    def load_chart(self):

        chart = self.get_container()
        chart_name = chart.get_name()

        content = chart.get_content()

        structure = dict(
            opacity=1.0,
            # opacity=0.5,
            visible=True,
            name=chart_name,
            bar=dict(
                visible=True,
                name=chart_name,
                opacity=0.75,
                layer="below",
                orientation='h',
                line=dict(
                    color='#ddd',
                    width=1,
                ),
            ),
            marker=dict(
                name="zodiac names",
                opacity=1.0,
                visible=True,
                color="#000",
            ),
            image=dict(
                x=0.015,
                sizex=0.025,
                sizey=0.025,
                xanchor="center",
                yanchor="middle",
                opacity=1.0,
                layer="above",
            ),
        )

        merge(
            structure,
            content,
        )

    def get_data(self):
        return self.get_container()

astro/models/legend/zodiac/models.py
# coding=utf-8
"""
Created on 2020, December 16th
@author: orion
"""
import copy
from transcend.containers import Container
from transcend.models.zodiac.constants import STRUCTURE


class Model(Container):

    def __init__(self, data):
        super(Model, self).__init__(data)
        self.data = dict()
        self.process()

    def process(self):
        model = self.get_container()
        angles = model["angles"]

        self.data = copy.deepcopy(
            STRUCTURE
        )

        self.data['zodiac']['angles'] = angles
        self.data['zodiac']['labels'] = model["labels"]

    def get_angles(self):
        return self.data['zodiac']['angles']

    def get_labels(self):
        return self.data['zodiac']['labels']

    def get_data(self):
        return self.data

astro/planets/positions/ephemeris/models/astrological.py
# coding=utf-8
"""
Created on 2020, December 17th
@author: orion
"""
from astro.zodiac.astrological.constants import get_data as get_zodiac
from astro.planets.positions.ephemeris.models.base import Model as Base


class Model(Base):

    def __init__(self, start_date, end_date, freq, bodies, output_type="html", zodiac_type="tropical"):
        super(Model, self).__init__(
            start_date,
            end_date,
            freq,
            bodies,
            zodiac=get_zodiac(),
            output_type=output_type,
        )
        # initializations

        self.zodiac_type = ""

        # settings

        self.zodiac_type = zodiac_type

    def get_zodiac_type(self):
        return self.zodiac_type

astro/planets/positions/ephemeris/models/astronomical.py
# coding=utf-8
"""
Created on 2020, December 20th
@author: orion
"""
from astro.planets.positions.ephemeris.models.base import Model as Base

from astro.zodiac.astronomical.constants import get_data as get_zodiac


class Model(Base):

    def __init__(self, start_date, end_date, freq, bodies, output_type="html"):
        super(Model, self).__init__(
            start_date,
            end_date,
            freq,
            bodies,
            zodiac=get_zodiac(),
            output_type=output_type,
        )

    def get_zodiac_type(self):
        return self.zodiac_type

astro/templates/celebrity/index.html
{% extends "celebrity/base.html" %}
{% load i18n %}
{% load l10n %}
{% load static %}
{% load js %}
{% load crispy_forms_tags %}

{% block index %}

	<div id="celebrity-row" class="section">

        <div class="container" data-animation-effect="fadeIn">

            <h4>{% trans "Transit" %}</h4>
            <div class="space"></div>
            <div class="row">
                <div class="col-md-5">

                    <!--<input type="hidden" id="id_transit_date" class="form-control" name="str_transit_date">-->
                    <!--<input type="hidden" id="id_transit_time" class="form-control" name="str_transit_time">-->
                    <div class="cycles-tab">
                         <!--<h6>-->
                             <!--<a href="javascript:load_transit( {{ theme.id }}, '{{aspect.get_utc_centered_date_iso }}')">{% trans "Current transit" %}</a>-->
                         <!--</h6>-->
                        <form action="{% url 'theme:transit' theme.id %}" class="uniForm" method="post" id="id-new-transit-form">
                            <div class="row">
                                <div class="col-md-12">
                                    {% crispy parameters-form %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-5">
                                    {% crispy date_form %}
                                    <label class="requiredField" for="date">{% trans "New Transit Date" %}
                                        <span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="date" id="date" class="form-control" name="str_transit_date" onchange="set_new_date(value)" required>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label class="requiredField" for="time">{% trans "Time (local)" %}
                                        <span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="time" id="time" class="form-control black-text-color numberinput" name="str_transit_time" onchange="set_new_time(value)" required>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="">
                                        <button type="submit" class="btn btn-primary">{% trans "DISPLAY" %}</button>
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                            </div>
                        </form>
                    </div>
                    <div class="cycles-tab">
                        <h6>{% trans "Transits related to the following cycles of interest" %}</h6>
                        {% for cycle in cycles %}
                          <button class="cycles-tablinks" onclick="openCycle(event, '{{cycle.tab_name}}')">{{cycle.tab_name}}</button>
                        {% endfor %}
                    </div>

                    {% for cycle in cycles %}

                        <div id="{{cycle.tab_name}}" class="cycles-tabcontent">
                            <p>
                                {% if cycle.is_internal and cycle.aspect.is_conjunction %}
                                    {% blocktrans with name=cycle.aspect.name conjunction_type=cycle.aspect.conjunction_type orb=cycle.aspect.orb count counter=cycle.aspect.next|length %}
                                            One {{ conjunction_type }} {{ name }}
                                        {% plural %}
                                            List of {{ conjunction_type }} {{ name }}
                                    {% endblocktrans %}
                                {% else %}
                                    {% blocktrans with name=cycle.aspect.name conjunction_type=cycle.aspect.conjunction_type orb=cycle.aspect.orb count counter=cycle.aspect.next|length %}
                                            One {{ name }}
                                        {% plural %}
                                            List of {{ name }}
                                    {% endblocktrans %}

                                {% endif %}
                                (orb = {{ cycle.aspect.orb }})
                            </p>

                            <ul id="ul-cycle">
                                {% if cycle.is_internal and cycle.aspect.is_conjunction %}
                                    {% for next in cycle.aspect.next %}
                                        <li class="li-cycle"><span class="caret-cycle">{{ next.aspect.get_start_year }}</span>
                                            <ul class="nested-cycle-disabled">
                                                <li><a href="javascript:load_transit( {{ theme.id }}, '{{next.aspect.get_utc_centered_date_iso }}')">{{ next.aspect.start|localize }} / {{ next.aspect.end|localize  }}</a></li>
                                            </ul>
                                        </li>
                                    {% endfor %}

                                {% else %}
                                    {% for aspect in cycle.aspect.next %}
                                        <li class="li-cycle"><span class="caret-cycle">{{ aspect.get_start_year }}</span>
                                            <ul class="nested-cycle">
                                                <li><a href="javascript:load_transit( {{ theme.id }}, '{{aspect.get_utc_centered_date_iso }}')">{{ aspect.start|localize }} / {{ aspect.end|localize  }}</a></li>
                                            </ul>
                                        </li>
                                    {% endfor %}

                                {% endif %}
                            </ul>
                        </div>

                    {% endfor %}

                </div>
                <div class="col-md-7">
                    {% block transit %}
                    {% endblock %}
                </div>
            </div>

        </div>

	</div>

{% endblock %}

	<script type="text/javascript" src="{% static 'theme/js/date.js' %}"></script>
	<script type="text/javascript" src="{% static 'theme/js/transit.js' %}"></script>
    <script type="text/javascript" src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<script type="text/javascript" src="{% static 'theme/js/initialize.js' %}"></script>
	<script type="text/javascript" src="{% static 'theme/js/cycles.js' %}"></script>

	<script>

	set_default_transit_date("date", "time")
	if ({{show.tropical | js}}) {
			initialize("transit-tropical-wheel", graph_tropical, config);
	}
	if ({{show.sidereal | js}}) {
			initialize("transit-sidereal-wheel", graph_sidereal, config);
	}
	if ({{show.compounded | js}}) {
			initialize("transit-compounded-wheel", graph_compounded, config);
	}

	</script>

astro/templates/celebrity/theme.html
{% extends "base.html" %}
{% load i18n %}
{% load l10n %}
{% load static %}
{% load js %}
{% load crispy_forms_tags %}

{% block section %}

{% if theme %}

	<div id="celebrity-row" class="section">

        <div class="container" data-animation-effect="fadeIn">
            <div class="row">
                <h4>Thème : {{ theme.full_name }}, {{ theme.further_information }}</h4>
            </div>
            <div class="row">
                <script>
                     var config = {{graphics.config | safe}};
                </script>
                {% if show.tropical %}

                    <div class="col-md-7">

                        <div id="tropical-wheel">

                        </div>
                        <script>
                             var graph_tropical = {{graphics.tropical | safe}};
                        </script>
                    </div>

                {% endif %}

                {% if show.sidereal %}

                    <div class="col-md-7">

                        <div id="sidereal-wheel">

                        </div>
                        <script>
                             var graph_sidereal = {{graphics.sidereal | safe}};
                        </script>
                    </div>

                {% endif %}

                {% if show.compounded %}

                    <div class="col-md-7">

                        <div id="compounded-wheel">

                        </div>
                        <script>
                             var graph = {{graphics.compounded | safe}};
                        </script>
                    </div>

                {% endif %}

                <div class="col-md-5">
                    <p>Date de naissance : <b>{{ theme.date }}</b></p>
                    <p>Lieu de naissance : <b>{{ theme.location.city }}</b>, {{ theme.location.context }}</p>
                    <p>latitude : <b><i>{{ theme.location.latitude }}</i></b>, longitude : <b><i>{{ theme.location.longitude }}</i></b></p>
                    <div class="space"></div>
                    <h6>{% trans "Available customization" %}</h6>
                    <form action="{% url 'theme:theme' theme.id %}" class="uniForm" method="post" id="id-new-theme-form">
                         {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                {% crispy parameters-form %}
                            </div>
                        </div>
                        <div class="space"></div>
                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary">{% trans "DISPLAY" %}</button>
                            </div>
                        </div>
                    </form>
                    <!--<form action="{% url 'theme:transit' theme.id %}" class="uniForm" method="post" id="id-new-transit-form">-->
                        <!--<input type="hidden" id="id_timezone_offset" class="form-control" name="offset">-->
                        <!--<div class="row">-->
                            <!--<div class="col-md-5">-->
                                <!--<label class="requiredField" for="date">{% trans "New Transit Date" %}-->
                                    <!--<span class="asteriskField">*</span>-->
                                <!--</label>-->
                                <!--<div class="">-->
                                    <!--<input type="date" id="date" class="form-control" name="str_transit_date" required>-->
                                <!--</div>-->
                            <!--</div>-->
                            <!--<div class="col-md-4">-->
                                <!--<label class="requiredField" for="time">{% trans "Time (local)" %}-->
                                    <!--<span class="asteriskField">*</span>-->
                                <!--</label>-->
                                <!--<div class="">-->
                                    <!--<input type="time" id="time" class="form-control black-text-color numberinput" name="str_transit_time" required>-->
                                <!--</div>-->
                            <!--</div>-->
                        <!--</div>-->
                        <!--<div class="space"></div>-->
                        <!--<div class="row">-->
                            <!--<div class="col-md-12">-->
                                <!--<button type="submit" class="btn btn-primary">{% trans "DISPLAY" %}</button>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</form>-->
                </div>

            </div>

        </div>

	</div>


	{% block index %}

	{% endblock index %}

    <div class="row">
        <h6>
            <form action="{% url 'theme:generate_pdf' theme.id %}" method="post">
                {% csrf_token %}
                <span>Télécharger le rapport
                    <button class="btn-theme-download"><i class="fa fa-download"></i></button>
                </span>
            </form>
        </h6>
    </div>

{% else %}

    <div class="row">
        <div class="col-md-12">
            <p>Veuillez nous excuser, nous ne sommes pas en mesure d'afficher le thème demandé</p>
        </div>
    </div>

{% endif %}


{% endblock section %}


{% block extra_js %}

    <script type="text/javascript" src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<script type="text/javascript" src="{% static 'theme/js/initialize.js' %}"></script>
	<script type="text/javascript" src="{% static 'theme/js/celebrity/cycles.js' %}"></script>
	<script type="text/javascript" src="{% static 'theme/js/celebrity/settings.js' %}"></script>
	<script type="text/javascript" src="{% static 'theme/js/date.js' %}"></script>
	<script type="text/javascript" src="{% static 'theme/js/transit.js' %}"></script>

	<script>

	$('#id-new-transit-form').submit(function() {
       var date = new Date();
       document.getElementById("id_timezone_offset").value = date.getTimezoneOffset()
       return true; // return false to cancel form action
});

	if ({{show.tropical | js}}) {
			initialize("tropical-wheel", graph_tropical, config);
	}
	if ({{show.sidereal | js}}) {
			initialize("sidereal-wheel", graph_sidereal, config);
	}
	if ({{show.compounded | js}}) {
			initialize("compounded-wheel", graph_compounded, config);
	}
	</script>

{% endblock extra_js %}